"""add reminder table

Revision ID: 3edad1ae6dd9
Revises: a4009c5ef19c
Create Date: 2023-03-20 18:01:27.787675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3edad1ae6dd9'
down_revision = 'a4009c5ef19c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminders')
    # ### end Alembic commands ###
