"""Added notfound_fixed table.

Revision ID: a68ac58d66f1
Revises: 9dcc664be95b
Create Date: 2023-04-20 07:04:21.505134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68ac58d66f1'
down_revision = '9dcc664be95b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notfound_fixed',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notfound_fixed')
    # ### end Alembic commands ###
